load_mod_df_test = true

load_mod_wasplib = true
load_mod_nlist = true
load_mod_sbots = true
load_mod_poi = true
load_mod_tps_client = true
load_mod_cchat = true
load_mod_killaura = true
load_mod_autoeat = true
load_mod_autokey = true
load_mod_enderchest = true
load_mod_open_inv = true
load_mod_invutil = true
load_mod_farmtool = true
load_mod_basic_moves = true
load_mod_lavaalarm = true
load_mod_punchinv = true
load_mod_devtools = true
load_mod_fishbot = true
load_mod_witherbot = true
load_mod_mclminer = true
load_mod_mcl_find_strongholds = true
load_mod_litematica = true
load_mod_scaffold = true
load_mod_dte = true
load_mod_lockview = true
load_mod_headsaver = true
load_mod_invsaver = true
load_mod_antitower = true
load_mod_walls = true
load_mod_autoevade = true
load_mod_rhythmtp = true
