load_mod_al_test = true
load_mod_al_formspec = true
load_mod_wasplib = true
load_mod_nlist = true
load_mod_sbots = true
load_mod_poi = true
load_mod_tps_client = true
load_mod_combat = true
load_mod_autoeat = true
load_mod_farmtool = true
load_mod_basic_moves = true
load_mod_devtools = true
load_mod_fishbot = true
load_mod_autominer = true
load_mod_schembuilder = true
load_mod_place = true
load_mod_dte = true
load_mod_invsaver = true
load_mod_rhythmtp = true
load_mod_autocraft = true
load_mod_dig = true
load_mod_lua_async = true
load_mod_findbiome = true
load_mod_help = true
load_mod_clean_hud = true
load_mod_always_day = true
load_mod_event_logger = true
load_mod_session_logger = true
load_mod_inventory = true
load_mod_priv = true
load_mod_blockexchange = true
