load_mod_df_test = true

load_mod_wasplib = true
load_mod_nlist = true
load_mod_sbots = true
load_mod_poi = true
load_mod_tps_client = true
load_mod_cchat = false
load_mod_killaura = true
load_mod_autoeat = true
load_mod_autokey = false
load_mod_inv_open = false
load_mod_invutil = false
load_mod_farmtool = true
load_mod_basic_moves = true
load_mod_devtools = true
load_mod_fishbot = true
load_mod_witherbot = true
load_mod_mclminer = true
load_mod_mcl_find_strongholds = false
load_mod_litematica = true
load_mod_place = true
load_mod_dte = true
load_mod_invsaver = true
load_mod_rhythmtp = true
load_mod_autocraft = true
load_mod_dig = true
load_mod_lua_async = true
load_mod_findbiome = true
load_mod_help = true
load_mod_autoevade = false
load_mod_session_stats = false
load_mod_clean_hud = true
load_mod_always_day = true
load_mod_formspec_blocker = false
load_mod_entity_logger = false
load_mod_world_observer = false
load_mod_movement_display = false
load_mod_breath_alert = false
load_mod_formspec_modifier = false
load_mod_player_radar = true
load_mod_chest_stealer = false
load_mod_formspec_utils = true
load_mod_event_logger = true
load_mod_session_logger = true
load_mod_inventory = true
